In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.46894875, -0.10852121, -0.36577457,  0.3292187 , -0.35457352,
        -0.49672484,  0.40828297, -0.42591363, -0.03346881, -0.17013165]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.16214922, 0.09101707, 0.07037188, 0.14100383, 0.07116455,
        0.06173453, 0.15260476, 0.06626452, 0.098111  , 0.08557872]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.7849119

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 8s 3ms/step - loss: 0.2954 - accuracy: 0.9151
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1433 - accuracy: 0.9575
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1093 - accuracy: 0.9664
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0875 - accuracy: 0.9727
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0756 - accuracy: 0.9763


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0782 - accuracy: 0.9761 - 677ms/epoch - 2ms/step


[0.07823137193918228, 0.9761000275611877]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.9710099e-07, 6.9131256e-09, 5.7435350e-06, 2.3343688e-04,
        6.9584373e-12, 3.2115653e-07, 3.1567014e-14, 9.9975258e-01,
        3.7912987e-08, 7.4491923e-06],
       [2.1943047e-09, 2.3029113e-04, 9.9975604e-01, 1.3620540e-05,
        2.1275015e-14, 1.7855101e-08, 8.6932221e-09, 1.5038326e-14,
        1.0489234e-07, 1.8291381e-13],
       [6.9368429e-07, 9.9981481e-01, 4.8932998e-05, 1.8764715e-06,
        8.3226041e-06, 6.9347595e-07, 2.4639446e-06, 8.3268162e-05,
        3.8056754e-05, 8.5944640e-07],
       [9.9998581e-01, 1.4197094e-10, 3.6227218e-06, 9.2557357e-08,
        9.0566094e-10, 4.6352665e-07, 2.3587445e-06, 4.0867271e-06,
        1.2359131e-08, 3.5127528e-06],
       [4.4275595e-05, 1.7466962e-09, 2.1847588e-06, 2.5728289e-08,
        9.9467838e-01, 3.1687031e-07, 1.6201602e-05, 2.7592730e-05,
        4.3357554e-06, 5.2267164e-03]], dtype=float32)>